pipeline:
    name: RemotePipelineMain
    identifier: RemotePipelineMain
    projectIdentifier: RajathaTest
    orgIdentifier: default
    storeType: REMOTE
    remoteType: create
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: GitHubRajathaAppRepo
                build: <+input>
    stages:
        - stage:
              name: stg1
              identifier: stg1
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.CItestK8sConnectoryg7d1MipIx
                          namespace: harness-qa-delegate
                          automountServiceAccountToken: true
                          nodeSelector: {}
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: test1
                                identifier: test1
                                spec:
                                    connectorRef: account.CItestDockerConnectorV2fKLnZNlQ
                                    image: alpine
                                    shell: Sh
                                    command: <+input>
